CREATE TABLE IF NOT EXISTS "users" (
  "id" SERIAL PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "senha" VARCHAR(255) NOT NULL,
  "nome" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "tasks" (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "nome" VARCHAR(255) NOT NULL,
  "tempo" INTEGER NOT NULL,
  "ativa" BOOLEAN NOT NULL DEFAULT true,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
